-- Create an autocommand group for kitty_cursor
-- local kitty_cursor_group = vim.api.nvim_create_augroup("kitty_cursor", { clear = true })

-- Add an autocommand to change the cursor style on Colorscheme event
-- vim.api.nvim_create_autocmd("Colorscheme", {
--   group = kitty_cursor_group,
--   callback = function()
--     vim.opt.guicursor = "n-v-c-sm:block-Cursor,i-ci-ve:ver25-Cursor,r-cr-o:hor20-Cursor"
--   end,
-- })

--
-- vim.api.nvim_create_autocmd({ "BufNew", "BufEnter" }, {
--   group = vim.api.nvim_create_augroup("USER_HYPRLANG", {}),
--   pattern = "*.conf",
--   callback = function()
--     vim.cmd("set filetype=hyprlang")
--   end,
--   group = vim.api.nvim_create_augroup("USER_Illuminate", {}),
--   callback = function()
--     require("illuminate").invisible_buf()
--   end,
-- })
